import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

const wasmPlugin = {
	name: 'wasm',
	setup(build) {
		build.onResolve({ filter: /\.wasm$/ }, args => {
			if (args.resolveDir === '') return;
			// Use require.resolve for proper node_modules resolution.
			const resolved = require.resolve(args.path, { paths: [args.resolveDir] });
			return {
				path: resolved,
				namespace: 'wasm-binary',
			};
		});
		build.onLoad({ filter: /.*/, namespace: 'wasm-binary' }, async (args) => ({
			contents: await fs.promises.readFile(args.path),
			loader: 'binary',
		}));
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	plugins: [wasmPlugin],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
